hosts: [
  { host_ip: "200.200.200.200", host_name: "oracledb"},
  { host_ip: "200.200.200.201", host_name: "mysqldb"},
  { host_ip: "200.200.200.202", host_name: "postgrsqldb"},
  { host_ip: "200.200.200.203", host_name: "hybridDB"},
]

obsolete_services:
  - puppet
  - chef-client
