- name: MongoDB is running
  docker_container:
    restart_policy: always
    name: mongodb
    image:  mongo:latest
    ports: 
    - "49161:27017"
    privileged: yes
    env:
      TZ: Asia/Taipei
#      MONGODB_USERNAME: ude
#      MONGODB_PASSWORD: ude
#      MONGODB_DATABASE: ude
    volumes:
      - /data/mongodb:/data/db
  when: not skip_ui is defined
  tags: [mongodb]
