- name: messagebus user is added to the root group
  user:
    name: messagebus
    group: root
  register: user_result
  tags: [postgresql]

- name: sameersbn-postgresql:9.6-2
  docker_container:
    privileged: yes
    env:
#      DB_USER: ude
#      DB_PASS: ude 
#      DB_NAME: udedb
      DB_USER: redmine
      DB_PASS: redmine 
      DB_NAME: redmine
    image: sameersbn/postgresql:9.6-2
#    image: sameersbn/postgresql:9.4-4
    name: postgresql
    ports: 
    - "49160:22"
    - "49161:80"
    - "49162:5432"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/postgresql:/var/lib/postgresql
  tags: [postgresql]
 
