- name: sameersbn-postgresql:9.5-3
  docker:
#    image: sameersbn/postgresql:9.5-3
    image: 192.168.57.29:5000/postgresql:9.5-3
    name: postgresql
    ports: 
    - "49160:22"
    - "49161:80"
    - "49162:5432"
    privileged: yes
    environment:
      - DB_USER: postgres
      - DB_PASS: postgres
      - DB_NAME: testdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /vagrant/postgresql:/var/lib/postgresql
  when: not skip_ui is defined
  tags: [postgresql]
 
